# Generated by Django 6.0 on 2026-04-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='skill',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
